### ISSUE TITLE
Use return codes when a link fails

### ISSUE THREAD

**Issue by diegorondini** [scivision/linkchecker-markdown#12]
When using a pipeline it is useful to have return codes reflect if errors occurred. For example [Bitbucket pipelines fail when an executed command has a non-zero return code](https://stackoverflow.com/a/63204934/813810).

Please return non-zero after `linkcheckMarkdown` detects a broken link.

Thank you for this nice tool!

**Comment by scivision** [comment]
Yes this is a great idea, thanks!

**Comment by scivision** [comment]
done in v1.4.0
