### ISSUE TITLE
Feature request: ability to provide custom User-Agent string

### ISSUE THREAD

**Issue by int-ua** [scivision/linkchecker-markdown#3]
I see two reasons, ability to:
1. provide up-to-date UA
2. skew visitor statistics towards some desired OS and/or browser

For anyone who would like to change it manually after cloning repo:
https://github.com/scivision/linkchecker-markdown/blob/c9ed0e9d420b7ae01385c7bd0374df839ac22d00/linkcheckmd/base.py#L35

**Comment by scivision** [comment]
Good point, thanks
